baseurl = "https://tejendrapsingh.net/"
title = "Tejendra Pratap Singh"
author = "Tejendra Pratap Singh"
canonifyurls = true
relativeURLs = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

#googleAnalytics = "G-NH0PZWJWJN"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Tejendra Pratap Singh"
copyright = "© 2022 Tejendra Pratap Singh"
copyrightUrl = "https://tejendrapsingh.net/"
#faviconfile = "image/favicon.png"
#logofile = ""
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

# Google Analytics 4
GoogleAnalyticsID = "G-NH0PZWJWJN"

github = "tejendrapsingh"
twitter = "tejendrapsingh"
#linkedin = "tejendra-pratap-singh-01210889"
email = "singh.pratap.tejendra@gmail.com"
googlescholar = "citations?user=VZBZmLYAAAAJ&hl=en"
osf = "f6dcv"


[[menu.primary]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.primary]]
identifier = "research"
name = "Research"
url = "/research/"
weight = 2

[[menu.primary]]
identifier = "CV"
name = "CV"
url = "/pdf/CV_Tejendra_2.pdf"
weight = 3

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/post/"
weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
